nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
  service:
    type: ClusterIP
    port: 80

tomcat:
  replicaCount: 1
  image:
    repository: tomcat
    tag: 9.0
  service:
    type: ClusterIP
    port: 8080

mysql:
  architecture: standalone
  auth:
    rootPassword: rootpass123
    username: user
    password: userpass123
    database: mydb
  primary:
    service:
      type: ClusterIP
